# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a0da7d1d4fef532807f47d40a40cf196b49d8c5513d9727fbadecb4e59188c3576fa2b31ac150468a73cfcf439f389c269b4388bc5623fdd983b8a3d176e1d

test:
  secret_key_base: 784ae486eb067ef3fa09c05a42bfeaf11f594936406e4de5e6eaba9f2f83c75732ad81d363bcfdbf258a76e6b3f623086713486de8dea471a471b9450b2309ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
